### ISSUE TITLE
Error when trying to delete a survey with questions already created

### ISSUE THREAD

**Issue by imaadkhan87** [fydo23/mySurvey#7]
This is because of the FK constraint, the error message is below. is there a way to turn 'on delete cascade' on? 

CDbException

CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mySurvey_app`.`survey_question`, CONSTRAINT `survey_question_ibfk_1` FOREIGN KEY (`survey_ID`) REFERENCES `survey` (`id`)). The SQL statement executed was: DELETE FROM `survey` WHERE `survey`.`id`=3

**Comment by bethh** [comment]
I think it's a good idea, Imaad.  I'm a little concerned about changing things right before the demo, but this one might be necessary.  I'll get to it later today.

**Comment by fydo23** [comment]
CASCADE ON DELETE should solve this issue for us.

**Comment by fydo23** [comment]
The addForeignKeys docs have our answer.
http://www.yiiframework.com/doc/api/1.1/CDbMigration#addForeignKey-detail

Redefining the foreign key constraints in the following fashion  should do the trick:

```
 $this->addForeignKey('fk1', 'table1', 'foreign_id', 'table2', 'id','CASCADE','CASCADE');
```

**Comment by bethh** [comment]
Hi Fyodor,

Thank you!  This link was really helpful.

I have the migration created, and it seems to work on my database.  I'd like you to look over the code, just to be sure if you don't mind.  I wasn't exactly sure what to do on the "down" migration, so I just dropped the foreign key.

I'm thinking that it might wait until after the demo.  What are your thoughts on that?  Now, or later?

Beth  (code follows)

<?php

class m131017_140544_change_foreign_keys extends CDbMigration
{
    public function up()
    {
     $this->dropForeignKey('survey_question_ibfk_1', 'survey_question');
     $this->addForeignKey('surveyfk', 'survey_question', 'survey_id', 'survey', 'id','CASCADE','CASCADE');

```
}

public function down()
{
    $this->dropForeignKey(surveyfk, survey_question);
}

/*
// Use safeUp/safeDown to do migration with transaction
public function safeUp()
{
}

public function safeDown()
{
}
*/
```

}

**Comment by fydo23** [comment]
Beth,
I believe the FK names were different in the database_update migration you created the first time around. We also need to make sure to re-add the old droped FK in the down function.

Fyodor Wolf
Web Developer II
Boston University
T (617) 358-6996
fwolf@bu.edumailto:fwolf@bu.edu
http://www.bu.edu/tech/

[cid:31842D16-AE81-4CA5-AE42-9F550E5243E5@bu.edu]

On Oct 17, 2013, at 10:48 AM, bethh <notifications@github.com<mailto:notifications@github.com>> wrote:

<?php

class m131017_140544_change_foreign_keys extends CDbMigration
{
public function up()
{
$this->dropForeignKey('survey_question_ibfk_1', 'survey_question');
$this->addForeignKey('surveyfk', 'survey_question', 'survey_id', 'survey', 'id','CASCADE','CASCADE');

}

public function down()
{
$this->dropForeignKey(surveyfk, survey_question);
}

**Comment by bethh** [comment]
Hi Fyodor,

So where does this stand now?

Beth

**Comment by fydo23** [comment]
at some point this issue was resolved by one of the migrations.

**Comment by imaadkhan87** [comment]
Hey Fyodor, you seem to be on a roll!
I'm still getting the same error though. I synced with the latest master, dropped all my tables and ran all the migrations again, but I'm still getting the same error.

**Comment by fydo23** [comment]
Make sure that you have the 'm131017_234034_fk_cascading' migration
I committed the fixes to 'dev' branch.

**Comment by imaadkhan87** [comment]
I was using master, switched to dev and ran the migration and its working now! 
Thanks.
